version: '3'

services:
  server:
    container_name: docker-server
    build: ./docker/centos
    volumes:
      - ./web:/srv
    ports:
      - 8099:80
    working_dir: /srv
    depends_on:
      - db

  api:
    container_name: docker-api
    image: nginx
    ports:
      - 8098:80
    volumes:
      - ./api:/api
      - ./docker/api.conf:/etc/nginx/conf.d/default.conf
    working_dir: /api
    links:
      - php

  php:
    container_name: docker-php
    build: ./docker/api
    volumes:
      - ./api:/api

  db:
    container_name: docker-db
    build: ./docker/db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/db/data:/var/lib/mysql
#    ports:
#      - 3306:3306

  db2:
    container_name: docker-db2
    build: ./docker/db2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/db2/data:/var/lib/mysql
      - ./docker/db2/sql:/docker-entrypoint-initdb.d/
#    ports:
#      - 3307:3306

  composer:
    container_name: docker-composer
    image: composer:1.6
    command: bash -c 'composer dump-autoload && cd /srv && composer dump-autoload && tail -f /dev/null'
    volumes:
      - ./web:/app
      - ./api:/srv
